### PR TITLE
Different structs for create and update monitor

### PR DESCRIPTION
**Pull request by ssameeruh**
Since `URL` is not a required field while updating a monitor, I have separated the structs into create and update structs

### CODE REVIEW

**Review by sudodeo — COMMENTED** [review]
hey @ssameeruh, thank you for the PRs. is there a reason you want to have separate structs for creating and updating monitors?
they look pretty much the same to me(tbf, I just did a quick scan)

**Comment by ssameeruh** [comment]
Hi. So for the `MonitorUpdateReqBody` struct, `URL` is `optional` and Paused accepts a `pointer`. The `MonitorUpdateReqBody` is just the old one only renamed.

**Comment by sudodeo** [comment]
> 

okay, in that case, we can have a base struct that holds the common fields and then use the base struct in both `MonitorUpdateReqBody` and `MonitorCreateReqBody`. something like this

```
type MonitorBase struct {
    URL    string `json:"url"`
    MonitorType    string `json:"monitor_type"`
    .......
}


type MonitorCreateReqBody struct {
    MonitorBase
    URL string `json:"url"`
}

type MonitorUpdateReqBody struct {
    MonitorBase
    URL     *string `json:"url,omitempty"`
    Paused  *bool   `json:"paused,omitempty"`
}
```

**Comment by ssameeruh** [comment]
Yes, I actually thought about doing it that way first. But since in the BetterStack API, the fields are on the same level, in my opinion having nested structs would only complicate stuff further.

I agree, it feels a bit redundant, but it's only once and makes things easier while using the `CreateMonitor` and `UpdateMontior` methods

**Comment by sudodeo** [comment]
the fields aren't going to be nested hehe
golang will replace `MonitorBase` with all the fields in that struct. kind of like how spread operations work in javascript.

as long as you don't give the struct you're embedding a name, `MonitorUpdateReqBody`, for example will inherit all the fields from `MonitorBase`

**Comment by ssameeruh** [comment]
Ok. Could you please show that with an example ? I am relatively new to Golang so that's something I might not know. 

Because, upon implementing your way, It was infact more like nesting.

```
type MonitorBase struct {
	MonitorType         string          `json:"monitor_type,omitempty"`          
	PronounceableName   string          `json:"pronounceable_name,omitempty"`   
        .....
}

type MonitorCreateReqBody struct {
	MonitorBase
	URL string `json:"url"`
}

type MonitorUpdateReqBody struct {
	MonitorBase
	URL    string `json:"url,omitempty"`
	Paused *bool  `json:"paused,omitempty"`
}

```




```
	_, err = bs.UpdateMonitor("123", models.MonitorUpdateReqBody{
		MonitorBase: models.MonitorBase{
			MonitorType:         "",
			PronounceableName:   "",
			...
		},
		URL:         "",
		Paused:      nil,
	})

```

**Comment by sudodeo** [comment]
have you tested it out yet?

**Comment by ssameeruh** [comment]
What do mean by testing ? I mean while creating the models.MonitorUpdateReqBody struct, I am not able to enter 
`MonitorType` and `PronounceableName` attributes directly.

**Comment by sudodeo** [comment]
okay, i think i understand your concern. do you already have `MonitorType` and `PronounceableName` attributes in `MonitorBase`?

if yes, then there's no need to redefine in the update struct.

if that's not the issue and you mean, when creating the request to update monitors, then you have to define `MonitorType` and `PronounceableName` inside the embedded `MonitorBase` and not directly in `MonitorUpdateReqBody`

**Comment by ssameeruh** [comment]
> okay, i think i understand your concern. do you already have `MonitorType` and `PronounceableName` attributes in `MonitorBase`?

Yes. Please see my comment here : https://github.com/sudodeo/betterstack-go/pull/6#issuecomment-2403440612

**Comment by sudodeo** [comment]
yeah, i saw your comment. you're on the right track with your example. it looks like nesting but it isn't haha

**Comment by ssameeruh** [comment]
Ok, can you please fix it on your side ? Or provide a complete example with a test ? Thanks

**Comment by sudodeo** [comment]
yeah, i'll do that tomorrow. it's late here

**Comment by sudodeo** [comment]
@ssameeruh can you do a quick check to verify that you replaced `MonitorReqBody` across the codebase? just be sure there are no errors

**Comment by ssameeruh** [comment]
Yes, I couldn't find any occurrences of `MonitorReqBody`

**Comment by sudodeo** [comment]
alright, LGTM. thank you for the PR

**Review by sudodeo — APPROVED** [review]

**Pull request merged**
